// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanReviewState } from "./PlanReviewState";
import type { PlanStage } from "./PlanStage";
import type { TimedPlanStep } from "./TimedPlanStep";

export type ContinuousPlanning = {
/**
 * Host-assigned identity, retained across revisions and changed for a new task.
 */
id: string, version: number, objective: string, acceptance: string, stages: Array<PlanStage>, steps: Array<TimedPlanStep>, review: PlanReviewState, updatedAt: number, nextReviewAt: number, estimatedCompletionAt: number, reason: string, };
