// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectedMessage } from "./DirectedMessage";
import type { MessageRecipient } from "./MessageRecipient";

export type MessageBatch = {
/**
 * The source assistant message ID; block IDs append their one-based index.
 */
id: string, sender: MessageRecipient,
/**
 * Conversation in which this host-generated projection is presented.
 */
audience: MessageRecipient, messages: Array<DirectedMessage>, finalAnswer: boolean, };
