// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanStage = { id: string, title: string, acceptance: string, assumptions: Array<string>, estimateSeconds: number, };
