// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecutionOutputDeltaNotification } from "./CommandExecutionOutputDeltaNotification";
import type { FileChangeOutputDeltaNotification } from "./FileChangeOutputDeltaNotification";
import type { ItemCompletedNotification } from "./ItemCompletedNotification";
import type { ItemStartedNotification } from "./ItemStartedNotification";
import type { McpToolCallProgressNotification } from "./McpToolCallProgressNotification";
import type { TerminalInteractionNotification } from "./TerminalInteractionNotification";

/**
 * Only native tool activity crosses this boundary, never Implementer dialogue.
 */
export type SupervisorActivity = { "type": "itemStarted", "data": ItemStartedNotification } | { "type": "itemCompleted", "data": ItemCompletedNotification } | { "type": "commandOutput", "data": CommandExecutionOutputDeltaNotification } | { "type": "fileOutput", "data": FileChangeOutputDeltaNotification } | { "type": "terminalInteraction", "data": TerminalInteractionNotification } | { "type": "mcpProgress", "data": McpToolCallProgressNotification };
