// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupervisorState = { revision: number, implementerThreadId: string | null, executionId: string | null, stepId: string | null, paused: boolean, updatedAt: number, activitySequence: number, totalTokens: number, tokenBudget: number | null, };
