// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupervisorState = { revision: number, implementerThreadId: string | null, executionId: string | null, stepId: string | null,
/**
 * Project-local Markdown plan maintained by the host.
 */
planPath: string | null,
/**
 * Bounded attention carried independently of the model conversation.
 */
pendingAttention: string | null,
/**
 * Small host-owned notes that survive context compaction and model restarts.
 */
memory: Array<string>, paused: boolean, updatedAt: number, activitySequence: number, totalTokens: number, tokenBudget: number | null, };
