// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuousPlanning } from "./ContinuousPlanning";
import type { SupervisorState } from "./SupervisorState";

export type ThreadSupervisorUpdatedNotification = { threadId: string, observedAt: number, state: SupervisorState, plan: ContinuousPlanning | null, };
