// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupervisorActivity } from "./SupervisorActivity";

export type ThreadSupervisorActivityNotification = { threadId: string, implementerThreadId: string, executionId: string, stepId: string, title: string, sequence: number, createdAt: number, activity: SupervisorActivity, };
