// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSupervisorActivityNotification } from "./ThreadSupervisorActivityNotification";

export type ThreadSupervisorHistoryListResponse = { data: Array<ThreadSupervisorActivityNotification>, nextCursor: string | null, };
