// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinuousPlanning } from "./ContinuousPlanning";

export type ThreadPlanUpdatedNotification = { threadId: string,
/**
 * Server clock when this view was sent, including snapshots on resume.
 */
observedAt: number, plan: ContinuousPlanning, };
