// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanStepDefinition } from "./PlanStepDefinition";
import type { PlanStepState } from "./PlanStepState";

export type TimedPlanStep = { definition: PlanStepDefinition, state: PlanStepState, owner: string, initialEstimateSeconds: number, elapsedSeconds: number, startedAt: number | null, runningSince: number | null, submittedAt: number | null, completedAt: number | null, evidence: Array<string>, };
